# baseURL: "https://ossig.netlify.com/"
disableKinds: ["taxonomy", "taxonomyTerm"]
languageCode: en-us
title: OHBM Open Science SIG
theme: hugo-fresh

params:
  navbarlogo:
    # Logo (from /images/logos/___)
    image: logos/ossig_logo.svg
    link: /
  font:
    name: "Open Sans"
    sizes: [400, 600]
  hero:
    # Main hero title
    title: The OHBM Open Science Special Interest Group
    # Hero subtitle (optional)
    subtitle: Dedicated to promoting and supporting open science within our community
    # Button text
    buttontext: Learn more
    # Where the main hero button links to
    buttonlink: "#openumbrella"
    # Hero image (from /images/___)
    image: illustrations/undraw_scrum_board.svg

  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
    - title: Our Team
      url: "/#OSSIG_team"
    - title: Join the OSSIG Committee
      url: "/elections"
    - title: Hackathon
      url: "https://ohbm.github.io/hackathon"
    - title: Call for fellows
      url: "/awards"
    - title: Open Science Room
      url: "https://ohbm.github.io/osr2022"
    - title: Sponsors
      url: "/sponsors"
    - title: Past members
      url: "/pastmembers"
  # - title: Bylaws
  #   url: https://docs.google.com/document/d/1_tfGJMtcwebVM06Z2AzNZ70JT1ID2S48fGCIqJwDyg0/edit?usp=sharing
  # - title: Join the OSSIG
  #   url: https://bit.ly/OHBMOSSIG2021Nominations

  hackathon:
    title: Save the date
    subtitle: It is coming... Finally.
    id: hackathon
    image: illustrations/landing_hackathon_2020.jpg
    buttonText: More info here
    buttonLink: https://github.com/ohbm/hackathon2020/blob/master/README.md

  team:
    title: Our team
    subtitle: The people behind the OSSIG
    id: OSSIG_team
    year: 2022
    # images (from /images/faces/2022/___.jpg)
    members:
      # chair, secretary, treasurer
      - name: Janine Bijsterbosch
        role: Chair
        image: janine_bijsterbosch
        affiliation: Department of Radiology, Washington University Medical School, Washington University in St Louis, USA
        twitter: https://twitter.com/PersonomicsLab
      - name: Johanna Bayer
        role: Secretary
        image: johanna_bayer
        affiliation: The University of Melbourne; Orygen, Melbourne
        twitter: https://twitter.com/likeajumprope
      - name: Benjamin De Leener
        role: Treasurer
        image: benjamin_de_leener
        affiliation: Polytechnique Montréal, Department of Computer Engineering and Software Engineering, TransMedTech Institute, CHU Sainte-Justine
        twitter: https://twitter.com/BenDeLeener

      # hackathon
      - name: Hao-Ting Wang
        role: Hackathon Chair
        image: haoting_wang
        affiliation: Centre de recherche de l'institut Universitaire de gériatrie de Montréal
        twitter: https://twitter.com/HaoTingW713
      - name: Stefano Moia
        role: Hackathon Deputy Chair
        image: stefano_moia
        affiliation: Ecole Polytechnique Federale de Lausanne
        twitter: https://www.twitter.com/SteMoia

      # OSR
      - name: Roza G. Bayrak
        role: Open Science Room Chair
        image: roza_gbayrak
        affiliation: Vanderbilt University, Department of Computer Science
        twitter: https://twitter.com/redgreenblues
      - name: Naomi L. Gaggi
        role: Open Science Room Deputy Chair
        image: naomi_lgaggi
        affiliation: City University of New York (CUNY) Graduate Center & CUNY School of Medicine at City College
        twitter: https://twitter.com/NaomiGaggi

      # inclusivity officer
      - name: Stephanie Noble
        role: Inclusivity Officer
        image: stephanie_noble
        affiliation: Department of Radiology & Biomedical Imaging, Yale University
        twitter: https://twitter.com/sNeuroble

      # Community Liason Officers
      - name: Subapriya Suppiah
        role: Community Liason Officer & Open Science Room Chair Elect
        image: subapriya_suppiah
        affiliation: Universiti Putra Malaysia
        twitter: https://twitter.com/SubapriyaSuppi1
      - name: Valentina Borghesani
        role: Community Liason Officer
        image: valentina_borghesani
        affiliation: Centre de recherche de l’Institut universitaire de Gériatrie de Montréal, Montréal, QC
        twitter: https://twitter.com/vborghesani

      # elect chair, secretary, treasurer
      - name: Koen Haak
        role: Chair Elect
        image: koen_haak
        affiliation: Donders Institute for Brain Cognition and Behaviour, Radboud University Medical Center, Nijmegen, The Netherlands
        twitter: https://twitter.com/KVHaak
      - name: Andrea Gondova
        role: Secretary Elect
        image: gondova_andrea
        affiliation: Université de Paris, NeuroDiderot INSERM; UNIACT Neurospin CEA; Paris, France
        twitter: https://twitter.com/reaGondova
      - name: Linden Parkes
        role: Treasurer Elect
        image: linden_parkes
        affiliation: University of Pennsylvania
        twitter: https://twitter.com/LindenParkes

  sponsors:
    title: Our sponsors
    subtitle: We are grateful for the generous support of our 2021 sponsors
    titleopp: Sponsorship opportunities
    tiersimage: /images/illustrations/ossig_sponsorship_tiers.jpg
    subtitleopp: Interested in supporting us? Please see our sponsorship opportunities below!
    sponsors:
      - name: Open Science Champion
        oursponsors:
          - name: "Openneuro"
            image: /images/logos/openneuro_logo.png
            height: 16em
            url: https://openneuro.org/
      - name: Hackathon Champion
        oursponsors:
          - name: "Courtois NeuroMod"
            height: 6em
            image: /images/logos/cneuromod_logo.svg
            url: https://www.cneuromod.ca/

      - name: Open Science Supporters
        oursponsors:
          - name: "Quebec Bio-Imaging Network"
            image: /images/logos/QBIN_logo.png
            url: https://www.rbiq-qbin.qc.ca/Accueil
            height: 7em
          - name: "MathWorks"
            image: /images/logos/mathworks_logo.png
            url: https://www.mathworks.com/
            height: 7em
      - name: Hackathon Supporters
        oursponsors:
          - name: "CONP"
            image: /images/logos/conp_logo.png
            url: https://conp.ca/
            height: 8em
          - name: "Wellcome Centre for Integrative Neuroimaging"
            image: /images/logos/logo_WIN_clear.png
            url: https://www.win.ox.ac.uk/
            height: 8em
      - name: Sponsors
        oursponsors:
          - name: "QMENTA"
            image: /images/logos/qmenta_logo.png
            url: https://www.qmenta.com/
            height: 8em
          - name: "Brainhack Marburg"
            image: /images/logos/bhmarburg_logo.png
            url: https://brainhack-marburg.github.io/
            height: 8em

  section2:
    title: Open science is an umbrella.
    subtitle: We're here to help grow the community supporting it.
    id: openumbrella
    features:
      - title: Open data
        text: Sharing neuroimaging data isn't easy, but we can make it easier. We're interested in understanding how OHBM members share data, where they encounter difficulties, and what kinds of new infrastruce and ethics can make next-generation data-sharing possible.
        # Icon (from /images/illustrations/icons/___.svg)
        icon: mouse-globe
      - title: Open code
        text: Analysis code is often a second-class citizen in neuroimaging research, but we can change that. We help to teach scientists best-practices in software development—and how those practices can result in real-world gains in research quality and output.
        icon: laptop-cloud
      - title: Open publishing
        text: Papers shouldn't hide behind paywalls. We want to help create solutions to enable new, open-acess platforms and to facilitate free information.
        icon: doc-sync


  footer:
    # Logo (from /images/logos/___)
    logo: ossig_logo.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
      - link: https://github.com/OHBM
        # Icons are from Font Awesome
        icon: github
      - link: https://twitter.com/ohbmopen
        icon: twitter
    bulmalogo: false
